spring:
  application:
    name: TDT-registry
    api-path: /api/v1
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME}:${DATABASE_PORT:5432}/tdt_registry
    username: tdt_db_owner
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    properties:
        hibernatedialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  ssl:
    key-store: classpath:certificates/springboot-https.p12
    key-store-password: your_key-store_password
    key-store-type: pkcs12
    key-alias: springboot-https
#    trust-store: classpath:certificates/newkeystore.jks
#    trust-store-password: your_key-store_password
    #trust-store-type: pkcs12
  port: ${PORT:8443}
  error:
    include-message: always

