spring:
  application:
    name: TDT-registry
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME}:${DATABASE_PORT}/tdt_registry
    username: tdt_db_owner
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    properties:
        hibernatedialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  ssl:
    key-store: classpath:springboot-https.p12
    key-store-password: your_key-store_password
    key-store-type: pkcs12
    key-alias: springboot-https
  port: 8443
